{% set name = "peer" %}
{% set version = "2.0.0-TEST1" %}

package:
  name: r-{{ name|lower }}
  version: TEST1

source:
  url: https://github.com/belowlab/peer/releases/download/{{ version }}/peer_2.0.tar.gz
  sha256: 44a7ae2e3d902487d2c73904a938983c568f093b8eb4efb5e083734ec5ae4180

build:
  skip: True  # [win]
  number: 0

  rpaths:
  - lib/R/lib/
  - lib/

requirements:
  build:
    # If your project compiles code (such as a C extension) then add the required compilers as separate entries here.
    # Compilers are named 'c', 'cxx' and 'fortran'.
    - {{ compiler('cxx') }}

  host:
    - r-base
    - r-devtools
    - r-bh
    - r-rcppeigen

  run:
    - r-base

test:
  commands:
    - $R -e "library('dplyr')"           # [not win]
    - "\"%R%\" -e \"library('dplyr')\""  # [win]

about:
  home: https://github.com/belowlab/peer
  summary: 'Factor analysis methods for gene expression profiles'
  description: |
    PEER is a collection of Bayesian approaches to infer hidden determinants and their effects 
    from gene expression profiles using factor analysis methods.


  # Remember to specify the license variants for BSD, Apache, GPL, and LGPL.
  # Use the SPDX identifier, e.g: GPL-2.0-only instead of GNU General Public License version 2.0
  # See https://spdx.org/licenses/
  license: GPL-2.0-or-later
  # The license_family, i.e. "BSD" if license is "BSD-3-Clause". 
  # Optional
  license_family: GPL
  # It is required to include a license file in the package,
  # (even if the license doesn't require it) using the license_file entry.
  # Please also note that some projects have multiple license files which all need to be added using a valid yaml list.
  # See https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#license-file
  license_file: LICENSE

extra:
  recipe-maintainers:
    # GitHub IDs for maintainers of the recipe.
    # Always check with the people listed below if they are OK becoming maintainers of the recipe. (There will be spam!)
    - pettyalex
