{% set name = "peer" %}
{% set version = "2.0.0-TEST1" %}

package:
  name: python-{{ name|lower }}
  version: TEST1

source:
  url: https://github.com/belowlab/peer/releases/download/{{ version }}/peer-2.0.0.tar.gz
  sha256: 3a98d48d1f8dde7515dd7fa5f11bba2b81eb9d341c4372a836e711b25c757233

build:
  skip: True  # [win]
  number: 0
  script_env:
  - SETUPTOOLS_USE_DISTUTILS=local # Python 3.12 does not have distutils in the stdlib anymore

requirements:
  build:
    - {{ compiler('cxx') }}
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
    - python                                # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
    - numpy
    - boost
    - eigen
  run:
    - python
    - {{ pin_compatible("numpy") }}

test:
  commands:
    - python -c "import peer"

about:
  home: https://github.com/belowlab/peer
  summary: 'Factor analysis methods for gene expression profiles'
  description: |
    PEER is a collection of Bayesian approaches to infer hidden determinants and their effects 
    from gene expression profiles using factor analysis methods.


  # Remember to specify the license variants for BSD, Apache, GPL, and LGPL.
  # Use the SPDX identifier, e.g: GPL-2.0-only instead of GNU General Public License version 2.0
  # See https://spdx.org/licenses/
  license: GPL-2.0-or-later
  # The license_family, i.e. "BSD" if license is "BSD-3-Clause". 
  # Optional
  license_family: GPL
  # It is required to include a license file in the package,
  # (even if the license doesn't require it) using the license_file entry.
  # Please also note that some projects have multiple license files which all need to be added using a valid yaml list.
  # See https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#license-file
  license_file: LICENSE

extra:
  recipe-maintainers:
    # GitHub IDs for maintainers of the recipe.
    # Always check with the people listed below if they are OK becoming maintainers of the recipe. (There will be spam!)
    - pettyalex
