{% set name = "alglib" %}
{% set version = "4.01.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://www.alglib.net/translator/re/alglib-{{ version }}.cpp.gpl.tgz
  sha256: 95e8ea41b32c92346f49a694759e786c5f3a1087b401a9259ef592c0eea4befb
  patches:
    - patches/01_add_cmake.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - ninja # Usable on win, mac, linux

test:
  commands:
    - test_c
    - test_i

about:
  home: https://www.alglib.net/
  summary: 'A cross-platform numerical analysis and data processing library'
  description: |
    ALGLIB is a cross-platform numerical analysis and data processing library. It supports five programming languages 
    (C++, C#, Java, Python, Delphi) and several operating systems (Windows and POSIX, including Linux).

  license: GPL-2.0-or-later
  license_family: GPL
  license_file: gpl2.txt

extra:
  recipe-maintainers:
    - pettyalex
